database:
  dialect: "postgresql"
  host: "192.168.193.129"
  port: 5432
  user: "postgres"
  password: "Ymj20040312@"
  dbname: "phase3_platform"
  maxOpenConns: 100     # 最大连接数
  maxIdleConns: 10      # 最大空闲连接数
  connMaxLifetime: 60   # 连接最大存活时间(秒)

